menu:
- {name: 'teaching', url: '/courses'}
- {name: 'publications', url: '/publications'}
- {name: 'people', url: '/people'}
- {name: 'reading group', url: '/reading_group'}
- {name: 'cv', url: '/cv.pdf'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Hadi Mustafa', title: 'PhD (Co-Advised with Dr. Teagyu Kim)', department: 'College of Information Sciences and Technology', url: 'https://arslan8.github.io/nowebsite.html'}
- {name: 'Michael P. Rooney', title: 'MS (Co-Advised with Dr. Dongyan Xu)', department: 'Computer Science at Purdue', url: 'https://michaelprooney.github.io/'}
- {name: 'Danielle L. Daniel', title: 'PhD (D.Eng, Currently at UNITED STATES AIR FORCE)', department: 'Computer Science and Engineering', url: 'https://arslan8.github.io/nowebsite.html'}
- {name: 'Sagor Sikdar', title: 'PhD (Co-Advised with Dr. Teagyu Kim)', department: 'Computer Science and Engineering', url: 'https://arslan8.github.io/nowebsite.html'}
- {name: 'Muhammad Hammad Bashir', title: 'PhD', department: 'Computer Science and Engineering', url: 'https://muhammadhammad001.github.io/'}
- {name: 'Changyul Lee', title: 'PhD (Co-Advised with Dr. Teagyu Kim)', department: 'College of Information Sciences and Technology', url: 'https://blog.serendipia.pe.kr/'}
- {name: 'Colin Smith', title: 'PhD', department: 'Computer Science and Engineering', url: 'https://arslan8.github.io/nowebsite.html'}
- {name: 'Evan English', title: 'BS (Co-Advised with Dr. Dongyan Xu)', department: 'Computer Science at Purdue', url: 'https://arslan8.github.io/nowebsite.html'}

alums:
- {name: 'Seongjin Kim - Now at Theori', title: 'BS (Co-Advised with Dr. Teagyu Kim)', department: 'College of Information Sciences and Technology', url: 'https://arslan8.github.io/nowebsite.html'}
- {name: 'Nimai Patel - Now at Lucid Motors', title: 'MS', department: 'Computer Science and Engineering', url: 'https://arslan8.github.io/nowebsite.html'}



courses:
- {name: '[CMPSC-597] Advanced Software Security - Spring 26', url: 'Advanced_Software_Security_spring26'}
- {name: '[CMPSC-597] Embedded Systems Security - Fall 25', url: 'embedded-systems-security-fa26'}
- {name: '[CMPSC-473] Operating Systems - Spring 25', url: 'operating-systems-sp25'}


social:
- {icon: 'github', link: 'https://github.com/Arslan8'}
- {icon: 'twitter', link: 'https://twitter.com/Arslan0o0'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/arslankhan52/'}

contacts:
- {name: 'Arslan Khan', title: 'Assistant Professor', department: 'Computer Science and Engineering', institution: 'Pennsylvania State University', institution_address: 'W209 Westgate Building, University Park, PA 16802', phone: '+1 (814)-856-1042', email: 'arslankhan@psu.edu', office: 'w359', image: 'assets/img/contact.jpg'}
